name: Generate contribution trail

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

jobs:
  cook:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%231e3ec8&color_dots=transparent,%23dce3ff,%23b5c1f7,%237d91e8,%233f5fd6
            dist/github-contribution-grid-snake-dark.svg?color_snake=%239daeff&color_dots=transparent,%232e344d,%234b5682,%236f82c2,%239daeff

      - name: Publish animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
